version: "3"
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/app/client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "3001:3001"
